import type { Metadata } from "next";
import "../../../app/globals.css";

export const metadata: Metadata = {
  title: "DesertBoard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased overflow-x-hidden h-screen overflow-y-hidden`}>{children}</body>
    </html>
  );
}
