import mongoose from "mongoose";

const AboutSchema  = new mongoose.Schema({
    metaTitle:{
        type:String
    },
    metaDescription:{
        type:String
    },
    bannerImage:{
        type:String
    },
    bannerAlt:{
        type:String
    },
    who_we_are:{
        type:String,
        required:true
    },
    core_value:{
        title:{
            type:String
        },
        content:{
            type:String,
        },
        image:{
            type:String,
        },
        altTag:{
            type:String,
        },
        cards:[
            {
                logo:{type:String},
                title:{type:String},
                logoAlt:{type:String}
            },
        ],
        seals:[{
            logo:{type:String}
        }]
    },
    strength_and_vision:{
        content:{
            type:String,
        },
        image:{
            type:String,
        },
        altTag:{
            type:String,
        },
        clients:[
            {
                logo:String
            },
        ]
    },
    history:[{
        year:{
            type:String,
        },
        title:{
            type:String,
        },
        image:{
            type:String,
        },
        altTag:{
            type:String,
        },
        content:{
                type:String
        },
    }]
})

export default mongoose.models.About || mongoose.model("About",AboutSchema)