import type { Metadata } from "next";
import { Urbanist, Inter } from "next/font/google";
import "../globals.css";
import Navbar from "../component/common/NavBars/Navbar";
import Footer from "../component/common/Footer";
const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Add necessary weights
});
import parse from 'html-react-parser';

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "BUILDING CO. (BEST) L.L.C",
  description: "Generated by create next app",
};

export const dynamic = 'force-dynamic'

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const tagResponse = await fetch(`${process.env.BASE_URL}/api/admin/tags`);
  const tagData = await tagResponse.json();
  return (
    <html lang="en">
      <head>{parse(tagData.tag.headerScript)}</head>
      <body className={`${urbanist.variable} ${inter.variable} antialiased`}>
      {parse(tagData.tag.bodyScript)}
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
